### ISSUE TITLE
Please share configuration for docker-compose

### ISSUE THREAD

**Issue by limpbrains** [messari/docker-zcash-core#1]
Hi

Thanks for this docker-image!
I'm trying to use it to run tests inside docker-compose like this:

```
version: '3'

services:
  testproject:
    build: .
    command: python3 testproject/manage.py test cc
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - zcashd

  zcashd:
    image: messari/zcash-core:2.0.3
    command: -printtoconsole -regtest=1 -rpcuser=root -rpcpassword=toor -server=1 -rest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0
    ports:
      - "18232:18232"
    expose:
      - "18232"
```

And I'm always getting `403 Forbidden` error when trying to execute some api call from testproject to zcashd.

Do you have a working example, could you please share it.

I only have such problem with zcashd. Bitcoin, litecoin, dash - all of them are working fine.
